### ISSUE TITLE
Your take on my code is extremely fucked

### ISSUE THREAD

**Issue by ghost** [Mezque/CustomLoadAudio#2]
[Your using Melonlogger.Instance without making it :trollface:](https://github.com/Mezque/CustomLoadAudio/blob/4413aa0354ebef7594173218a96bb0d30ec3ebf2/Main.cs#L21). [The mod supports any file path but your still creating an unnecessary file path.](https://github.com/Mezque/CustomLoadAudio/blob/4413aa0354ebef7594173218a96bb0d30ec3ebf2/Main.cs#L13)

**Comment by ghost** [comment]
I'd also like to mention CyanTabby is gangstalking you :trollface:

**Comment by Mezque** [comment]
> [Your using Melonlogger.Instance without making it :trollface:](https://github.com/Mezque/CustomLoadAudio/blob/4413aa0354ebef7594173218a96bb0d30ec3ebf2/Main.cs#L21). [The mod supports any file path but your still creating an unnecessary file path.](https://github.com/Mezque/CustomLoadAudio/blob/4413aa0354ebef7594173218a96bb0d30ec3ebf2/Main.cs#L13)

1, You're wrong ": MelonMod" gives you an instanced logger, you only need to create new ones if it's not inside of a class that's ": MelonMod" or if it's not static or if you wish to define a custom name different then the title of your mod.

2, That's the default path for convenience's sake, it's not unnecessary really. Anyhow even if you don't use it its just another junk file thrown into the Userdata folder that gets forgotten about anyways lol.

**Comment by Mezque** [comment]
> I'd also like to mention CyanTabby is gangstalking you :trollface:

And I know this kekw they star a lot of vrchat related repository's

**Comment by ghost** [comment]
They haven't starred mine 😢
