### ISSUE TITLE
Doesn't work in most recent update

### ISSUE THREAD

**Issue by GuusDeKroon** [Mezque/CustomLoadAudio#3]
I'm afraid that in the new update, this mod doesn't work

**Comment by Mezque** [comment]
I should have time to look into this and fix it this weekend, thanks for the notice! :)

I'll let you know once I've fixed it I might work on it later today or tomorrow.

**Comment by Mezque** [comment]
This is now fixed in release 3 https://github.com/Mezque/CustomLoadAudio/releases/tag/Release3 @GuusDeKroon Sorry it took me a while to get done, I didn't have a whole lot of time and was dealing with some things irl and have just had some time to fix my mods now.
